{{ config(
    materialized='table',
    schema='FINAL'
) }}

SELECT
    PICKUP_DATE,

    COUNT(*) AS TRIP_COUNT,

    SUM(TRIP_DISTANCE) AS TOTAL_DISTANCE,

    AVG(TRIP_DISTANCE) AS AVG_TRIP_DISTANCE,

    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,

    AVG(TOTAL_AMOUNT) AS AVG_TRIP_AMOUNT,

    AVG(TRIP_DURATION_MINUTES)
        AS AVG_TRIP_DURATION_MINUTES,

    AVG(SPEED_KMH)
        AS AVG_SPEED_KMH,

    AVG(TIP_RATE)
        AS AVG_TIP_RATE,

    SUM(PASSENGER_COUNT)
        AS TOTAL_PASSENGERS

FROM {{ ref('int_clean_trips') }}

GROUP BY
    PICKUP_DATE